SELECT * FROM customer;

SELECT COUNT (*) FROM customer;

-- Business Requirements:

-- Q1. What is the total revenue generated by male vs female customers?

SELECT gender, SUM (purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG (purchase_amount) FROM customer);


-- Q3. WHich are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND (AVG (review_rating::numeric),2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between standard and express shipping?

SELECT shipping_type, ROUND (AVG (purchase_amount::numeric),2) AS shipping_type
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers?

SELECT subscription_status, 
	COUNT (customer_id) AS total_customers,
	ROUND (AVG (purchase_amount::numeric),2) AS avg_spend,
	SUM (purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend, total_revenue;


-- Q6. Which 5 products have the highest percentage of purchase with discount applied ?

SELECT item_purchased,
	COUNT (CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discount_applied,
	ROUND (COUNT (CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) :: numeric, 2) AS discount_percent
FROM customer
GROUP BY item_purchased
LIMIT 5;


-- Q7. Segement customers into New, Returning, and Loyal based on their total number of previous purchase, and show the count of each segment ?

SELECT
	CASE		
		WHEN previous_purchases = 1 THEN 'New Customers'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Customers'
		ELSE 'Loyal Customers'
	END AS customer_segement,
	COUNT (*) AS customer_count
FROM customer
GROUP BY customer_segement;


-- Q8. What are the top 3 most purchased products within each category?

WITH products AS
(
SELECT category, item_purchased,
	COUNT (item_purchased) AS most_purchased,
	RANK () OVER (PARTITION BY category ORDER BY COUNT (item_purchased) DESC) AS rnk
FROM customer
GROUP BY category, item_purchased
)
SELECT * FROM products
WHERE rnk <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
	COUNT (customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
	SUM (purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
